#!/usr/bin/env node
// build-legal.mjs — generates the SMS/voice program legal pages:
//   EN: /privacy/  /terms/      ES: /privacidad/  /terminos/
//
// These pages exist primarily to satisfy carrier requirements for the
// A2P 10DLC campaign behind the rcsd.info text/voice lines
// (EN (650) 482-8912, ES (650) 399-7203): the campaign registration links to
// /privacy/ and /terms/, and carrier reviewers verify the URLs resolve and
// contain CTIA-required program disclosures (program name, frequency,
// "msg & data rates", HELP/STOP, support contact, no-marketing-share pledge).

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { headMeta, siteNav, siteFooter } from './html-parts.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.join(__dirname, '..', 'docs');

const PAGE_CSS = `
.legal-wrap { max-width: 760px; margin: 0 auto; padding: 2rem 1.25rem 4rem; }
.legal-wrap h1 { font-family: 'Fraunces', serif; margin-bottom: .25rem; }
.legal-wrap .updated { color: #5a6b5d; font-size: .9rem; margin-bottom: 2rem; }
.legal-wrap h2 { font-family: 'Fraunces', serif; margin: 2rem 0 .5rem; font-size: 1.25rem; }
.legal-wrap p, .legal-wrap li { line-height: 1.6; }
.legal-wrap ul { padding-left: 1.25rem; }
`;

const UPDATED = '2026-07-19';

function page({ lang, title, description, canonical, altLangHref, bodyHtml }) {
  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
${headMeta({
    title,
    description,
    canonical,
    ogLocale: lang === 'es' ? 'es_US' : 'en_US',
    hreflang: [
      { lang: lang === 'es' ? 'en' : 'es', href: altLangHref },
    ],
    pageCSS: PAGE_CSS,
  })}
</head>
<body>
${siteNav({ activePage: null, lang, altLangHref })}
<main class="legal-wrap">
${bodyHtml}
</main>
${siteFooter({ lang })}
</body>
</html>
`;
}

// ---------------------------------------------------------------- EN privacy
const privacyEN = `
<h1>Privacy Policy</h1>
<p class="updated">Last updated: ${UPDATED}</p>

<p>rcsd.info is an independent public-information website about the Redwood City
School District, operated by Primatech Paper Co LLC. It is not affiliated with
or endorsed by the district. This policy covers the website and the rcsd.info
text and voice information lines (English: (650) 482-8912, Spanish:
(650) 399-7203).</p>

<h2>What we collect</h2>
<ul>
<li><strong>Website:</strong> we don't have accounts and we don't set tracking
cookies. Our hosting provider (Cloudflare) keeps standard server logs.</li>
<li><strong>Text &amp; voice lines:</strong> when you text, call, or message us,
we receive your phone number and the content of your question. We keep
conversation logs so the service works (e.g., follow-up questions) and to
prevent abuse.</li>
</ul>

<h2>How we use it</h2>
<p>Your question is processed, including by AI (artificial intelligence)
services, solely to generate an answer from public school-district data. We use
logs to improve answer quality and to keep the service safe.</p>

<h2>What we don't do</h2>
<p><strong>No mobile information will be shared with third parties or
affiliates for marketing or promotional purposes.</strong> We do not sell your
phone number or messages. We do not send marketing. The service replies only
when you contact it first.</p>

<h2>Children</h2>
<p>The service is intended for parents, guardians, and community members —
adults. Please don't submit personal information about students.</p>

<h2>Contact</h2>
<p>Questions? Email <a href="mailto:team@rcsd.info">team@rcsd.info</a>.</p>

<p><a href="/terms/">Text-line Terms of Service</a></p>
`;

// ---------------------------------------------------------------- EN terms
const termsEN = `
<h1>Text &amp; Voice Line Terms of Service</h1>
<p class="updated">Last updated: ${UPDATED}</p>

<h2>Program description</h2>
<p>The <strong>rcsd.info information line</strong> answers questions about the
Redwood City School District — calendars, lunch menus, school info, and school
board meetings — using publicly available data. English: (650) 482-8912.
Spanish: (650) 399-7203. You can call or text either number.</p>

<p>rcsd.info is an independent community project operated by Primatech Paper Co
LLC. It is <strong>not</strong> an official channel of the Redwood City School
District. Answers are generated by AI and may contain mistakes — always confirm
important details with your school or the district
(<a href="https://www.rcsdk8.net" target="_blank" rel="noopener">rcsdk8.net</a>).</p>

<h2>Message frequency &amp; rates</h2>
<p>This is a conversational service: it only replies to questions you send.
Message frequency varies with your usage. <strong>Message and data rates may
apply</strong> according to your mobile plan. Carriers are not liable for
delayed or undelivered messages.</p>

<h2>Opting out</h2>
<p>Reply <strong>STOP</strong> at any time to stop receiving messages. After
you text STOP, we will send one final message confirming you are opted out.</p>

<h2>Help &amp; support</h2>
<p>Reply <strong>HELP</strong> for help, or email
<a href="mailto:team@rcsd.info">team@rcsd.info</a>.</p>

<h2>Privacy</h2>
<p>See our <a href="/privacy/">Privacy Policy</a>. No mobile information will
be shared with third parties or affiliates for marketing or promotional
purposes.</p>
`;

// ---------------------------------------------------------------- ES privacy
const privacyES = `
<h1>Política de Privacidad</h1>
<p class="updated">Última actualización: ${UPDATED}</p>

<p>rcsd.info es un sitio web independiente con información pública sobre el
Distrito Escolar de Redwood City, operado por Primatech Paper Co LLC. No es un
sitio oficial del distrito. Esta política cubre el sitio web y las líneas de
texto y voz de rcsd.info (inglés: (650) 482-8912, español: (650) 399-7203).</p>

<h2>Qué información recibimos</h2>
<ul>
<li><strong>Sitio web:</strong> no hay cuentas y no usamos cookies de rastreo.
Nuestro proveedor de hosting (Cloudflare) guarda logs normales del
servidor.</li>
<li><strong>Líneas de texto y voz:</strong> cuando nos mandas un texto o nos
llamas, recibimos tu número de teléfono y tu pregunta. Guardamos el historial
de la conversación para que el servicio funcione bien y para prevenir
abuso.</li>
</ul>

<h2>Cómo la usamos</h2>
<p>Tu pregunta se procesa, incluso con servicios de AI (inteligencia
artificial), solamente para darte una respuesta con datos públicos del
distrito escolar.</p>

<h2>Lo que NO hacemos</h2>
<p><strong>No compartimos tu información móvil con terceros ni afiliados para
marketing o promociones.</strong> No vendemos tu número ni tus mensajes. No
mandamos publicidad. El servicio solo responde cuando tú escribes primero.</p>

<h2>Niños</h2>
<p>El servicio es para papás, tutores y miembros de la comunidad — adultos. Por
favor no mandes información personal de estudiantes.</p>

<h2>Contacto</h2>
<p>¿Preguntas? Escríbenos a
<a href="mailto:team@rcsd.info">team@rcsd.info</a>.</p>

<p><a href="/terminos/">Términos de Servicio de la línea de texto</a></p>
`;

// ---------------------------------------------------------------- ES terms
const termsES = `
<h1>Términos de Servicio — Línea de Texto y Voz</h1>
<p class="updated">Última actualización: ${UPDATED}</p>

<h2>¿Qué es este servicio?</h2>
<p>La <strong>línea de información de rcsd.info</strong> contesta preguntas
sobre el Distrito Escolar de Redwood City — calendarios, menús de almuerzo,
información de escuelas y reuniones de la mesa directiva — usando datos
públicos. Inglés: (650) 482-8912. Español: (650) 399-7203. Puedes llamar o
mandar texto a cualquiera de los dos números.</p>

<p>rcsd.info es un proyecto comunitario independiente operado por Primatech
Paper Co LLC. <strong>No</strong> es un canal oficial del Distrito Escolar de
Redwood City. Las respuestas las genera AI y pueden tener errores — siempre
confirma los detalles importantes con tu escuela o con el distrito
(<a href="https://www.rcsdk8.net" target="_blank" rel="noopener">rcsdk8.net</a>).</p>

<h2>Frecuencia de mensajes y tarifas</h2>
<p>Este es un servicio de conversación: solo responde a las preguntas que tú
mandas. La frecuencia de mensajes depende de tu uso. <strong>Pueden aplicar
tarifas de mensajes y datos</strong> según tu plan de teléfono. Las compañías
de teléfono no son responsables por mensajes retrasados o no entregados.</p>

<h2>Para cancelar</h2>
<p>Responde <strong>STOP</strong> en cualquier momento para dejar de recibir
mensajes. Después de tu STOP, te mandamos un último mensaje confirmando la
cancelación.</p>

<h2>Ayuda</h2>
<p>Responde <strong>HELP</strong> para ayuda, o escríbenos a
<a href="mailto:team@rcsd.info">team@rcsd.info</a>.</p>

<h2>Privacidad</h2>
<p>Lee nuestra <a href="/privacidad/">Política de Privacidad</a>. No
compartimos tu información móvil con terceros ni afiliados para marketing o
promociones.</p>
`;

const pages = [
  {
    out: 'privacy', lang: 'en',
    title: 'Privacy Policy — rcsd.info',
    description: 'Privacy policy for the rcsd.info website and text/voice information lines.',
    canonical: 'https://rcsd.info/privacy/',
    altLangHref: '/privacidad/',
    bodyHtml: privacyEN,
  },
  {
    out: 'terms', lang: 'en',
    title: 'Text & Voice Line Terms of Service — rcsd.info',
    description: 'Terms of service for the rcsd.info text and voice information lines.',
    canonical: 'https://rcsd.info/terms/',
    altLangHref: '/terminos/',
    bodyHtml: termsEN,
  },
  {
    out: 'privacidad', lang: 'es',
    title: 'Política de Privacidad — rcsd.info',
    description: 'Política de privacidad del sitio rcsd.info y de sus líneas de texto y voz.',
    canonical: 'https://rcsd.info/privacidad/',
    altLangHref: '/privacy/',
    bodyHtml: privacyES,
  },
  {
    out: 'terminos', lang: 'es',
    title: 'Términos de Servicio — Línea de Texto — rcsd.info',
    description: 'Términos de servicio de las líneas de texto y voz de rcsd.info.',
    canonical: 'https://rcsd.info/terminos/',
    altLangHref: '/terms/',
    bodyHtml: termsES,
  },
];

for (const p of pages) {
  const dir = path.join(DOCS, p.out);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), page(p));
  console.log(`wrote docs/${p.out}/index.html`);
}
